# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import system_pb2 as system__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in system_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingServiceStub(object):
    """BOOKING SERVICE
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBooking = channel.unary_unary(
                '/tennis.BookingService/CreateBooking',
                request_serializer=system__pb2.CreateBookingRequest.SerializeToString,
                response_deserializer=system__pb2.BookingDto.FromString,
                _registered_method=True)
        self.GetBooking = channel.unary_unary(
                '/tennis.BookingService/GetBooking',
                request_serializer=system__pb2.GetBookingRequest.SerializeToString,
                response_deserializer=system__pb2.BookingDto.FromString,
                _registered_method=True)
        self.StreamActiveBookings = channel.unary_stream(
                '/tennis.BookingService/StreamActiveBookings',
                request_serializer=system__pb2.StreamActiveBookingsRequest.SerializeToString,
                response_deserializer=system__pb2.BookingDto.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """BOOKING SERVICE
    """

    def CreateBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamActiveBookings(self, request, context):
        """server-side streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBooking,
                    request_deserializer=system__pb2.CreateBookingRequest.FromString,
                    response_serializer=system__pb2.BookingDto.SerializeToString,
            ),
            'GetBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooking,
                    request_deserializer=system__pb2.GetBookingRequest.FromString,
                    response_serializer=system__pb2.BookingDto.SerializeToString,
            ),
            'StreamActiveBookings': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamActiveBookings,
                    request_deserializer=system__pb2.StreamActiveBookingsRequest.FromString,
                    response_serializer=system__pb2.BookingDto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tennis.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tennis.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """BOOKING SERVICE
    """

    @staticmethod
    def CreateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tennis.BookingService/CreateBooking',
            system__pb2.CreateBookingRequest.SerializeToString,
            system__pb2.BookingDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tennis.BookingService/GetBooking',
            system__pb2.GetBookingRequest.SerializeToString,
            system__pb2.BookingDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamActiveBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tennis.BookingService/StreamActiveBookings',
            system__pb2.StreamActiveBookingsRequest.SerializeToString,
            system__pb2.BookingDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ScheduleServiceStub(object):
    """SCHEDULE SERVICE
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSchedule = channel.unary_unary(
                '/tennis.ScheduleService/GetSchedule',
                request_serializer=system__pb2.GetScheduleRequest.SerializeToString,
                response_deserializer=system__pb2.ScheduleResponse.FromString,
                _registered_method=True)


class ScheduleServiceServicer(object):
    """SCHEDULE SERVICE
    """

    def GetSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedule,
                    request_deserializer=system__pb2.GetScheduleRequest.FromString,
                    response_serializer=system__pb2.ScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tennis.ScheduleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tennis.ScheduleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScheduleService(object):
    """SCHEDULE SERVICE
    """

    @staticmethod
    def GetSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tennis.ScheduleService/GetSchedule',
            system__pb2.GetScheduleRequest.SerializeToString,
            system__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReviewServiceStub(object):
    """REVIEW SERVICE
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateReview = channel.unary_unary(
                '/tennis.ReviewService/CreateReview',
                request_serializer=system__pb2.CreateReviewRequest.SerializeToString,
                response_deserializer=system__pb2.ReviewDto.FromString,
                _registered_method=True)


class ReviewServiceServicer(object):
    """REVIEW SERVICE
    """

    def CreateReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateReview': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReview,
                    request_deserializer=system__pb2.CreateReviewRequest.FromString,
                    response_serializer=system__pb2.ReviewDto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tennis.ReviewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tennis.ReviewService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReviewService(object):
    """REVIEW SERVICE
    """

    @staticmethod
    def CreateReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tennis.ReviewService/CreateReview',
            system__pb2.CreateReviewRequest.SerializeToString,
            system__pb2.ReviewDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CourtServiceStub(object):
    """COURT SEARCH SERVICE
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchCourts = channel.unary_unary(
                '/tennis.CourtService/SearchCourts',
                request_serializer=system__pb2.SearchCourtsRequest.SerializeToString,
                response_deserializer=system__pb2.SearchCourtsResponse.FromString,
                _registered_method=True)


class CourtServiceServicer(object):
    """COURT SEARCH SERVICE
    """

    def SearchCourts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CourtServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchCourts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCourts,
                    request_deserializer=system__pb2.SearchCourtsRequest.FromString,
                    response_serializer=system__pb2.SearchCourtsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tennis.CourtService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tennis.CourtService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CourtService(object):
    """COURT SEARCH SERVICE
    """

    @staticmethod
    def SearchCourts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tennis.CourtService/SearchCourts',
            system__pb2.SearchCourtsRequest.SerializeToString,
            system__pb2.SearchCourtsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
